### PR TITLE
Make sure reconstructed image's origin is a multiple of spacing

### PR DESCRIPTION
**Pull request by dzenanz**

### CODE REVIEW

**Comment by dzenanz** [comment]
Review, merge?

**Comment by lassoan** [comment]
Thanks for the reminder. I'll review this later tonight.

**Comment by dzenanz** [comment]
Ping @lassoan @cpinter @adamrankin

**Comment by adamrankin** [comment]
I am not familiar enough with volume reconstruction to identify what unintended consequences this change may have. I will leave it for Andras as this is his area.

**Comment by lassoan** [comment]
Sorry for the delay, we've reviewed this with @Sunderlandkyl and will merge very soon.

**Comment by Sunderlandkyl** [comment]
@dzenanz Can you test the changes in 16ea843 to see if they have the desired effect?

**Comment by dzenanz** [comment]
It does the same thing. Thanks!

**Comment by Sunderlandkyl** [comment]
Great! would you mind updating the baselines for the volume reconstruction testing data? http://perkdata.cs.queensu.ca/CDash/viewTest.php?onlyfailed&buildid=96349

**Comment by dzenanz** [comment]
Done. [PR20](https://github.com/PlusToolkit/PlusLibData/pull/20)

**Comment by Sunderlandkyl** [comment]
Thanks!

**Pull request closed without merging**
