### PR TITLE
Scoliosis transverse process enhancer

### PR DESCRIPTION
**Pull request by travers-bryan**
Moved code from vtkPlusTransverseProcessEnhancer to vtkPlusBoneEnhancer. 

vtkPlusBoneEnhancer is currently written in a way that makes it is easy to create sub-classes of it. These sub-classes can be used for detecting bones that have specific qualities. vtkPlusBoneEnhancer now detects all areas that could be bone, but contains no false-positive removal. vtkPlusTransverseProcessEnhancer is one such sub-class, that does all the same things as vtkPlusBoneEnhancer, but with the additional steps of comparing the shadow areas, and looking for bones with suspicious placement.

### CODE REVIEW

**Comment by lassoan** [comment]
There are conflicts on this branch. Please rebase your branch on the latest master branch.

**Comment by travers-bryan** [comment]
I understand, I have fixed the issues and have cleaned up my branch. I will be making this updated pull request shortly.

**Comment by cpinter** [comment]
@lassoan Bryan is working on the new PR for quite a while now. I hope he can issue it very soon.

**Comment by cpinter** [comment]
Why did you close this PR?

**Pull request closed without merging**
