### PR TITLE
Reviving PreTMatrix attribute

### PR DESCRIPTION
**Pull request by dzenanz**
This is useful when multiple transforms need to be recorded which differ only by a constant offset.

### CODE REVIEW

**Comment by dzenanz** [comment]
@jamesobutler Can you test the updated code?

**Comment by jamesobutler** [comment]
Tested with the updates and it works. Thanks!

**Comment by dzenanz** [comment]
@lassoan @adamrankin Merge?

**Comment by lassoan** [comment]
PreT is not a valid transform name. Please specify a name that unambiguously tells what coordinate systems it transforms between. For example, BaseToEncoder.

Let us k ow if there is a strong reason to make an exception to the standard naming convention.

**Comment by jamesobutler** [comment]
@lassoan Dzenan issued an update that updated "PreTMatrix" to "BaseToEncoderMatrix".

**Comment by lassoan** [comment]
I missed that, sorry. I just made up BaseToEncoder name as an example. Is that the actual meaning of the transform?

**Comment by dzenanz** [comment]
There is one tracker and multiple transducers. These transducers will all have fixed and known offset relative to tracker. However the geometry might change over time, and we want each transducer's position to be written into the sequence file. Plus does not write constant transforms into sequence file so we "fake" multiple encoders by using this extra translation transform.

But this transform might have some other uses, so `TransducerToEncoder` would be misleading as a name. `BaseToEncoder` would be general enough and expresses the intended use to some extent.

**Comment by lassoan** [comment]
Thank you, I'm merging this now.

I've just found there is a variable "TransformationMatrix" just one line above - which is probably one of the least informative transformation matrix name possible. I would recommend to review coordinate system and transformation names throughout this class.

**Pull request merged**
