### PR TITLE
re #205: exchanging between BGR codification and RGB codification

### PR DESCRIPTION
**Pull request by carlos-luque**
I have fixed the frame RGB codification in the function vtkPlusOpenCVCaptureVideoSource::InternalUpdate().

### CODE REVIEW

**Comment by lassoan** [comment]
Thanks for the pull request.

@markasselin Could you test this to see if color appears as we expect and there is no significant performance impact? Thanks!

**Comment by adamrankin** [comment]
Just fyi that this is a GPU optimized function, and so performance will be dependent on the hardware available.

**Comment by lassoan** [comment]
If image data is in CPU memory then RGB<->BGR conversion is probably slower in GPU than using CPU MMX instructions. Hopefully, the OpenCV implementation is smart enough to choose GPU/CPU based on what is more efficient to use.

**Comment by adamrankin** [comment]
Confirmed with our student who worked with the NDI Vega RTSP stream that indeed the colours were reversed, as so this fixes that problem!

Thanks Carlos!

**Pull request merged**
