### PR TITLE
Removing old support in preparation of dependency updates

### PR DESCRIPTION
**Pull request by jamesobutler**
re https://github.com/PlusToolkit/PlusLib/issues/1004 to align standards and toolkits used in latest 3D Slicer

This is a PR associated with https://github.com/PlusToolkit/PlusBuild/pull/82

cc: @adamrankin, @Sunderlandkyl, @lassoan

### CODE REVIEW

**Comment by lassoan** [comment]
It would simplify things if we could remove these from the source code, but we still need Ultrasonix and StealthLink support. I think keeping the latest Plus version compatible is still the easiest solution. If we display meaningful error messages at configuration time when Ultrasonix and StealthLink is enabled and some incompatible options are chosen then we could avoid unexpected build errors.

**Comment by jamesobutler** [comment]
Is Ultrasonix or Stealthlink supported on a version of Windows currently supported?

**Comment by lassoan** [comment]
Yes, the client (that is in Plus) work on latest Windows 11 for both. The OS in the device is WinXP embedded for Ultrasonix (that must be connected to the network via firewall and direct internet access is disabled), StealthStation is using some recent Linux version.

**Comment by jamesobutler** [comment]
## Stealthlink
> StealthStation is using some recent Linux version.

Ok so StealthStation isn’t stuck using Windows 7/8? That’s what the below text at https://plustoolkit.github.io/download made it seem like.

> PlusApp-…-StealthLink-Win32: Package to be used for connecting to Medtronic navigation systems through StealthLink interface on 32/64-bit, Windows 7 and Windows 8 systems. Requires StealthLink license. Package is available on request.

## Ultrasonix
> The OS in the device is WinXP embedded for Ultrasonix (that must be connected to the network via firewall and direct internet access is disabled),

So one of the dependency build configuration options must still support Windows XP? The below text is from https://plustoolkit.github.io/download

> Supported on Windows 7 or Windows XP Embedded:
> 
> PlusApp-…-Ultrasonix-5.7-Win32: Package to be used on Ultrasonix systems (running on Windows XP embedded or Windows 7 operating system); running Ultrasonix Exam software version between 5.7.0 and 6.0.2. MicronTracker and Microsoft Media Foundation imaging devices are not supported. Executables are 32-bit applications.

**Comment by lassoan** [comment]
I've updated the documentation and download page to make things more clear (we only support Windows 10 and 11; except the Ultrasonix package, which we support on XP and XPe). Probably in a couple of years we can wind down Ultrasonix support, but it is still the only ultrasound system that has built-in electromagnetic tracking sensor in the transducer and has a research interface.

**Pull request closed without merging**
