### PR TITLE
re #1148 linking to necessary ITK dependency

### PR DESCRIPTION
**Pull request by adamrankin**
Cleaning up code

### CODE REVIEW

**Comment by adamrankin** [comment]
Is there a list variable for ITK IO targets?

**Comment by dzenanz** [comment]
Unfortunately, no. You have to manually list all the IO formats you want
linked. You can find the complete list here
<https://itk.org/Doxygen/html/classitk_1_1ImageIOBase.html>, by clicking on
the Inheritance Diagram.

Dženan Zukić, PhD, Senior R&D Engineer, Kitware (Carrboro, N.C.)

**Comment by adamrankin** [comment]
Obvious question, does the VTK reader have a similar target construction? If not, does it support enough file formats to be reasonable?

**Comment by adamrankin** [comment]
Ah, it has vtkIOImage at least...

**Comment by dzenanz** [comment]
vtkIOImage probably only supports .vtk. And VTK has a separate reader for each format, e.g. vtkPNGReader, vtkBMPReader etc and a switch statement to select between them.

**Comment by adamrankin** [comment]
Ok, how about a CMake loop that scans all ITK targets for "IO" in them, and links to those targets? We may catch some extra targets, but at least it's not ITK_LIBRARIES...

**Comment by lassoan** [comment]
Earlier we only supported nrrd and vtk and nobody complained. It's fine to just list a few file formats that we think people may want to use and we can add support for more, if requested.

**Comment by adamrankin** [comment]
This is for mask loading though, some people may want BMP or PNG as common paint tools output these formats.

**Comment by lassoan** [comment]
Sure, we can add support for bmp, png, jpg. No need for any fancy auto-explore mechanism. ITK's IO plugin infrastructure is fragile enough already (it's easy to forget about IO factory registration, etc).

**Comment by lassoan** [comment]
@dzenanz Is there a test that uses mask and fails if mask file loading fails?

**Comment by adamrankin** [comment]
So far, I have this:

# Scan ITK_LIBRARIES for targets with "IO" in them
SET(_itk_io_libraries)
FOREACH(_lib ${ITK_LIBRARIES})
  IF(${_lib} MATCHES "IO")
    LIST(APPEND _itk_io_libraries ${_lib})
  ENDIF()
ENDFOREACH()

It produces a reasonable list.

**Comment by adamrankin** [comment]
If we only want those file formats, then I'd vote we use VTK to keep our ITK dependencies to a minimum.

**Comment by lassoan** [comment]
I agree. VTK's IO is much simpler and more robust (no IO factory, plugins, no surprises at runtime), and fulfills our basic needs.

**Comment by adamrankin** [comment]
Does the ITK system scan files for headers, or is it also based on file extension?

**Comment by adamrankin** [comment]
@dzenanz What do you think, are the formats supported by VTK enough?

**Comment by dzenanz** [comment]
Well originally I had a code version which was using only vtkPNGReader, anticipating problems with lots of ITK IO dependencies. I was surprised when I didn't need to modify CMakeLists.txt for ITK to work! So I went ahead and submitted the version with ITK only.

**Comment by dzenanz** [comment]
#13 has only vtkPNGReader. To support merging of 3D scans, a reader supporting a 3D image format should be added. I don't have any such data to test with.

**Pull request merged**
