### PR TITLE
Fix compilation for Atracsys

### PR DESCRIPTION
**Pull request by hgueziri**
Fixing compiling issues with Atracsys FusionTrack SDK 4.4.1. It seems to be related to #446. 

Tested for FusionTrack on Ubuntu 18.04 and Windows 10.

### CODE REVIEW

**Comment by markasselin** [comment]
@hgueziri @drouin-simon  Nice work! 

Just a heads up I have some unmerged Atracsys updates here https://github.com/markasselin/PlusLib/commits/atr2 which you can take a look at as well which add some functionality. Plan is to add button streaming and video streaming before merging this branch, but if you need these changes sooner I can merge them now.

**Comment by hgueziri** [comment]
Oh, the fix is already present in your branch. You can probably ignore the PR. When are you planning to merge it?
Also, I see that you added remote control. If it is functional, it will be really interesting to have. Thanks!

**Comment by markasselin** [comment]
I have tested the remote control on a spryTrack and on a fusionTrack system, and it worked in both cases. I will send a PR tonight with the update which fixes the build with 4.4.1 as well as the remote control work. 
I'm still working on the button sending and video streaming, but these are also coming.

@hgueziri thanks for reminding me!

**Comment by markasselin** [comment]
See https://github.com/PlusToolkit/PlusLib/pull/635.

Since this is a duplicate I will close this PR. Thanks @hgueziri for your work on this!

**Pull request closed without merging**
