### PR TITLE
ENH: add cosmic ray correction

### PR DESCRIPTION
**Pull request by dzenanz**

### CODE REVIEW

**Comment by adamrankin** [comment]
Just let us know when to merge.

**Comment by dzenanz** [comment]
I think this is ready to merge, but I defer to @jrojasUNC.

**Comment by dzenanz** [comment]
... and Juan is on vacation until January. I guess this will keep pending for two more weeks.

**Review by jrojasUNC — APPROVED** [review]
Sorry for the delay. I just tested this and it looks good.

**Pull request merged**
