### PR TITLE
addresses #1185 use write_basic_package_version_file instead of custo…

### PR DESCRIPTION
**Pull request by dkuegler**
…m Version file

### CODE REVIEW

**Comment by dkuegler** [comment]
cf. Pull request 42
since this pull request compiles fine for me, I would like to get Access to the jenkins Logs, how do I do that? I do not have a user name...

**Comment by lassoan** [comment]
Thanks a lot, your changes look good and will merge soon.
@adamrankin Do you think you can fix the automatic builds or we should disable them for now?

**Comment by adamrankin** [comment]
I would disable them. The problems arise from the volume reconstruction tests having different results on different platforms. I am unfamiliar with that code.

**Comment by lassoan** [comment]
If it's only due to the VR tests (that are kind of expected to have minor differences on different computers due to floating-point computations) then we could disable them for these automatic tests.

**Comment by lassoan** [comment]
👍 Thank you for your contribution

**Pull request merged**
