### PR TITLE
Reducing log spam when 5dof tools are used, and 6th dof jumps all ove…

### PR DESCRIPTION
**Pull request by adamrankin**
…r the place

(example, optically tracked stylus with collinear fiducials)

### CODE REVIEW

**Comment by lassoan** [comment]
The code change looks harmless, but you should not see jumps in the spinning angle when you move around a tool. Probably there is a single orientation of the stylus where these jumps may happen, and so you should set up your system in a way that you don't get into that specific orientation during normal use.

**Comment by adamrankin** [comment]
Unfortunately with the 8700248 this situation happens constantly (collinear fiducials, NDI system is unable to reliably produce roll value). The net result is that the roll angle jumps randomly and produces this interpolation warning (as it should) constantly, flooding the log.

The solution is to use a different stylus or pattern, which is my final solution, but this helps me in development (and others is they want to use this aluminum machined stylus from NDI).

**Comment by lassoan** [comment]
This should be ideally fixed in NDI software. Spinning can be restricted by always spin so that the spheres face "up" or any other chosen direction in some coordinate system. NDI Aurora 5-DOF sensors are stabilized like this. I don't know why they don't do it for this tracker/marker.

We could do this stabilization in Plus, too, but it would be simpler if they did it in their software because they know the sphere configuration, so they know what rotation axis should be constrained.

**Comment by adamrankin** [comment]
That would be great, but won't likely happen. Imo it's not worth implementing in Plus, as there are more valuable things to accomplish. For now reducing the log spam is enough for me, and shouldn't affect any other cases where it happens for a genuine reason.

**Comment by lassoan** [comment]
I agree. We cannot wait for NDI, don't have the time to implement instead of them, so a workaround is good enough (or don't use such tools or trackers).

**Pull request merged**
