### PR TITLE
ENH update options for atracsys trackers

### PR DESCRIPTION
**Pull request by atracsys-sbt**
Following the release of atracsys sdk 4.7.x for both sprytrack and fusiontrack devices, the options have been updated.
New control options have been added: Integration Time, Compression Threshold and Enable IR Strobe

### CODE REVIEW

**Comment by Sunderlandkyl** [comment]
Can you rebase the branch on the latest master?

**Comment by atracsys-sbt** [comment]
I'm not sure what you mean, it says my fork is up-to-date with the upstream repo....

**Comment by Sunderlandkyl** [comment]
This branch can't currently be merged due to conflicts, probably because all but one of the commits in this PR have already been added to Plus.

If rebasing didn't skip the existing commits, you can fix by checking out the latest master and cherry picking the commit you want to add onto it.

**Comment by lassoan** [comment]
GitHub reports the error like this:

image

**Comment by atracsys-sbt** [comment]
Sorry, I'm still kind of new to github. I think this is ok now, can you confirm ?

**Pull request merged**
